# Generated by Django 5.2.1 on 2025-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='changeme', max_length=128),
            preserve_default=False,
        ),
    ]
