# Generated by Django 5.2.1 on 2025-05-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='ia_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.user'),
        ),
    ]
