# Generated by Django 5.2.1 on 2025-05-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_statistic_ia_draws_statistic_ia_loses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='ia_draws_difficile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_draws_facile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_draws_moyen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_loses_difficile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_loses_facile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_loses_moyen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_wins_difficile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_wins_facile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='ia_wins_moyen',
            field=models.IntegerField(default=0),
        ),
    ]
